#!/bin/bash

#Author: Anil
#description: to upload the jenkins jobs logs in s3 bucket
#version: v1


JENKINS_HOME="/var/lib/jenkins"
S3_BUCKET="s3//bucket-name"  #put here s3 bucket name
DATE=$(date '+%Y-%m-%d')

#chek if aws cli is installed
if ! command -v aws &> /dev/null; then
	echo "AWS CLI is not installed.Please install to proceed."
	exit 1
fi


# Iterate through all job directories 
for job_dir in "$JENKINS_HOME/jobs/"*/; do
	job_name=$(basename "$job_dir")

	#iterate through build directories for the job
        for build_dir in "$job_dir/builds/*/; do
		#get build number and log file path
		build_number=$(basename "$build_dir")
		log_file="$build_dir/log"


		#check if log file exists and was created today
		if [ -f "$log_file" ] && [ "$(date -r "$log_file" +%Y-%m-%d)" == "$DATE" ]; then
	 		#upload log file to s3 with build number as the filename 
			aws s3 cp "$log_file" "$S3_BUCKET/$Job_name-$build_number.log" --only-show-errors
		
			if [ $? -eq 0 ]; then
				echo "uploaded: $job_name/$build_number to $S3_BUCKET/$job_name-$build_number.log"
			else
				echo "Failed to upload: $job_name/$build_number"
			fi
		fi
	done
done

